name: skin_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1  # Fixed typo

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.0
  http: ^1.2.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  image_path: assets/icon/app_icon.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/images/
